DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('register/', user_view.register, name = 'register'),
    path('profile/', user_view.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'user/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'user/logout.html'), name = 'logout'),
    
    # path('password_change/done/', 
    #     auth_views.PasswordChangeDoneView.as_view(template_name = 'user/password_change_done.html'), 
    #     name = 'password_change_done'),

    # path('password_change/', 
    #     auth_views.PasswordChangeView.as_view(template_name = 'user/password_change.html'),
        # name = 'password_change'),

    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name = 'user/password_reset.html'), 
        name = 'password_reset'),

    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name = 'user/password_reset_done.html'),
        name = 'password_reset_done'),

    path('password_reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name = 'user/password_reset_confirm.html'),
        name ='password_reset_confirm'),

    path('password_reset/complete',
        auth_views.PasswordResetCompleteView.as_view(template_name = 'user/password_reset_complete.html'),
        name = 'password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from user import views as user_view
from .views import (PostDetailView, 
                    PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView)

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name = 'home'),
    path('user/<str:username>', UserPostListView.as_view(), name = 'user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name = 'post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('post/new/', PostCreateView.as_view(), name = 'post-create'),
    path('movie/', views.movie, name = 'movie'),
    path('sport/', views.sport, name = 'sport'),
    path('travel/', views.travel, name = 'travel'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100)
    content = models.TextField()
    date_posted = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs = {'pk': self.pk})

    
    

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.OneToOneField(User, unique = True, on_delete=models.CASCADE) 
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]

class ProfileUpdateForm(forms.ModelForm):
    # profile = forms.ImageField()
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView, 
                                DetailView, 
                                CreateView,
                                UpdateView,
                                DeleteView,)

# Create your views here.
def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username = self.kwargs.get('username'))
        return Post.objects.filter(author = user).order_by('-date_posted')

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    

 

def movie(request):
    return render(request, 'blog/movie.html')

def sport(request):
    return render(request, 'blog/sport.html')

def travel(request):
    return render(request, 'blog/travel.html')

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile

def register(request):

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created! You are now able to log in')
            return render(request, 'user/login.html')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form': form})


@login_required
def profile(request):

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'user/profile.html', context)

blog/templates/blog/base_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:movie' %}">Movie</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:sport' %}">Sport</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:travel' %}">Travel</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">About</a>
                <a class="dropdown-item" href="#">Contact</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Vision</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">bath.s_</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:post-create' %}">Post!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
          {% block body_block %}
          {% endblock %}
      </div>
</body>
</html>

blog/templates/blog/home.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    {% for post in posts %}
        <article class="media content-section container jumbotron mt-2">
            <img src="{{ post.author.profile.image.url }}" alt="author" class="rounded-circle article-img mr-2" style = "width: 50px; height: 50px;">
            <div class="media-body">
                <div class="article-metadata">
                    <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2"> {{ post.author}} </a>
                    <small class="text-muted"> {{ post.date_posted}} </small>
                </div>
                <h2><a href="{% url 'blog:post-detail' post.id %}" class="article-title"> {{post.title}} </a></h2>
                <p class="article-content"> {{post.content}} </p>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{num}}" class="btn btn-info mb-4">{{num}}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}

    {% endif %}

    {% endblock %}

blog/templates/blog/movie.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <h1>Hello this is movie page!</h1>
    {% endblock %}

blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Delete Post
                </legend>
                <h2>Are you sure you want to delete ? {{object.title}}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>

            </div>
        </form>
        
    </div>
    {% endblock %}

blog/templates/blog/post_detail.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
        <article class="media content-section container jumbotron mt-3">
            <img src="{{ object.author.profile.image.url }}" alt="author" class="rounded-circle article-img mr-2" style = "width: 50px; height: 50px;">
            <div class="media-body">
                <div class="article-metadata">
                    <a href="{% url 'blog:user-posts' object.author.username %}" class="mr-2"> {{ object.author}} </a>
                    <small class="text-muted"> {{ object.date_posted}} </small>
                
                    {% if object.author == user %}
                    <div>
                        <a href="{% url 'blog:post-update' object.id %}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                        <a href="{% url 'blog:post-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1">Delete</a>
                    </div>
                    {% endif %}
                </div>
                <h2 class="article-title">{{object.title}}</h2>
                <p class="article-content"> {{object.content}} </p>
            </div>
        </article>
    {% endblock %}

blog/templates/blog/post_form.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
{% load crispy_forms_tags %}
    {% block body_block %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    What's on Your mind !
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post </button>
            </div>
        </form>
    </div>
    {% endblock %}

blog/templates/blog/sport.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <h1>Hello this is sport page!</h1>
    {% endblock %}

blog/templates/blog/travel.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <h1>Hello this is Explorer page!</h1>
    {% endblock %}

blog/templates/blog/user_posts.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section container jumbotron mt-2">
            <img src="{{ post.author.profile.image.url }}" alt="author" class="rounded-circle article-img mr-2" style = "width: 50px; height: 50px;">
            <div class="media-body">
                <div class="article-metadata">
                    <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2"> {{ post.author}} </a>
                    <small class="text-muted"> {{ post.date_posted}} </small>
                </div>
                <h2><a href="{% url 'blog:post-detail' post.id %}" class="article-title"> {{post.title}} </a></h2>
                <p class="article-content"> {{post.content}} </p>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Previous</a>
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{num}}" class="btn btn-info mb-4">{{num}}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}

    {% endif %}

    {% endblock %}

user/templates/user/login.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
{% load crispy_forms_tags %}
    {% block body_block %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                   Have an Account?
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset'%}"> Forget Password ?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account? <a href="{% url 'register' %}" class="ms-2">Sign up Now !</a>    
            </small>

        </div>
    </div>
    {% endblock %}

user/templates/user/logout.html
{% extends 'blog/base_blog.html' %}
    {% block body_block%}
        <h2>You've been logged out.</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}" class="ml-2">Log in agian!</a>
            </small>
        </div>
    {% endblock %}

user/templates/user/password_reset.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
{% load crispy_forms_tags %}
    {% block body_block %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                   Reset Password
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request</button>
            </div>
        </form>
    </div>
    {% endblock %}

user/templates/user/password_reset_complete.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <div class="alert alert-info">
        Complete!
        <small class="text-muted">
            <a href="{% url 'login' %}" class="ms-2">Sign In</a>    
        </small>
    </div>
    {% endblock %}

user/templates/user/password_reset_confirm.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
{% load crispy_forms_tags %}
    {% block body_block %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                   Reset Password
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Confirm</button>
            </div>
        </form>
    </div>
    {% endblock %}

user/templates/user/password_reset_done.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
    {% block body_block %}
    <div class="alert alert-info">
        An email has been sent with instruction to reset your password.
    </div>
    {% endblock %}

user/templates/user/profile.html
{% extends 'blog/base_blog.html' %}
{% load crispy_forms_tags %}
    {% block body_block%}
    <div class="content-section">
        <div class="media container jumbotron mt-3">
          <img class="rounded-circle account-img mr-2 mt-3" src="{{ user.profile.image.url }}">
          <div class="media-body">
            <h2 class="account-heading ml-5 mt-5">{{ user.username }}</h2>
            <p class="text-secondary ml-5">{{ user.email }}</p>
          </div>
          <div class="media-body mr-5">
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">
                      Profile Info:
                  </legend>
                  {{ u_form|crispy }}
                  {{ p_form|crispy }}
              </fieldset>
              <div class="form-group">
                  <button class="btn btn-outline-info" type="submit">Update</button>
              </div>
          </form>
          </div>
        </div>
      </div>

    
    {% endblock %}

user/templates/user/register.html
<!DOCTYPE html>
{% extends 'blog/base_blog.html' %}
{% load crispy_forms_tags %}
    {% block body_block %}
    <h1>Hello this is Register page</h1>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Join Today !!
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up </button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an Account? <a href="{% url 'login' %}" class="ms-2">Sign In</a>    
            </small>

        </div>
    </div>
    {% endblock %}